name: android_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_bluetooth_serial: ^0.4.0
  crypto: ^3.0.3
  provider: ^6.1.1
  permission_handler: ^11.3.1
  geolocator: ^10.1.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
